name: pexels
version: 0.1.2
description: Unofficial wrapper of Pexels REST API for the Dart Language.
author: Kennedy Tochukwu Ekeoha <ekeohak@gmail.com>
repository: https://github.com/xenoken/pexels
homepage: https://github.com/xenoken/pexels
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.5
dev_dependencies:
  test : ^1.17.3
